spring.application.name: teste
caminho.lista: src/main/resources/lista.csv
spring.datasource.dbcp2.driver-class-name: com.h2database
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
